# Constants variables for Voltrix-SpMM project
PROJECT_NAME_FULL = "Voltrix-SpMM"
PROJECT_NAME_ABBR = "Voltrix"
PROJECT_NAME_FULL_LOWER = "voltrix-spmm"
PROJECT_NAME_ABBR_LOWER = "voltrix"


# Voltrix-SpMM Environment variables
DEBUG_FLAG = "VOLTRIX_JIT_DEBUG"
NVCC_COMPILER_FLAG = "VOLTRIX_NVCC_COMPILER"
CACHE_DIR_FLAG = "VOLTRIX_CACHE_DIR"
PTXAS_VERBOSE_FLAG = "VOLTRIX_PTXAS_VERBOSE"
JIT_PRINT_NVCC_COMMAND_FLAG = "VOLTRIX_JIT_PRINT_NVCC_COMMAND"
PRINT_AUTOTUNE_FLAG = "VOLTRIX_PRINT_AUTO_TUNE"



